version: '3.8'

services:
    postgers:
        container_name: postgres
        image: postgres:14.5-alpine
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
    backend:
        container_name: backend
        build:
            context: ./backend
        depends_on:
            - postgers
        restart: unless-stopped
        ports:
            - '${API_PORT}:3001'
        environment:
            - API_PORT=${API_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=postgres
            - JWT_SECRET=${JWT_SECRET}
    frontend:
        container_name: frontend
        build:
            context: ./frontend
        depends_on:
            - backend
        restart: unless-stopped
        ports:
            - '3000:3000'
